CUSTOM_ID_REGEX = r'^[a-zA-Z0-9]*$'

CUSTOM_ID_LENGTH = 6
MAX_CUSTOM_ID_LENGTH = 16
MAX_ORIGINAL_ID_LENGTH = 512

INDEX_TEMPLATE = 'index.html'
PAGE_NOT_FOUND_TEMPLATE = '404.html'
INTERNAL_SERVER_ERROR_TEMPLATE = '500.html'
